services:
  bot:
    build: .
    container_name: store_check_bot
    restart: always
    environment:
      - TZ=Asia/Novosibirsk
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_USER_IDS=${ADMIN_USER_IDS}
    volumes:
      # Сохраняем базу данных (монтируем корневую папку проекта)
      - ./:/app
      # Исключаем папку src из монтирования (опционально, для производительности)
      - /app/src
    working_dir: /app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge